/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    Badge: typeof import('./src/components/ui/Badge.vue')['default']
    Button: typeof import('./src/components/ui/Button.vue')['default']
    Card: typeof import('./src/components/ui/Card.vue')['default']
    CategoryForm: typeof import('./src/components/categories/CategoryForm.vue')['default']
    CategoryList: typeof import('./src/components/categories/CategoryList.vue')['default']
    CustomerForm: typeof import('./src/components/customers/CustomerForm.vue')['default']
    CustomerList: typeof import('./src/components/customers/CustomerList.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoadingSpinner: typeof import('./src/components/ui/LoadingSpinner.vue')['default']
    Modal: typeof import('./src/components/ui/Modal.vue')['default']
    QuoteForm: typeof import('./src/components/quotes/QuoteForm.vue')['default']
    QuoteList: typeof import('./src/components/quotes/QuoteList.vue')['default']
    QuoteServiceForm: typeof import('./src/components/quotes/QuoteServiceForm.vue')['default']
    QuoteServiceList: typeof import('./src/components/quotes/QuoteServiceList.vue')['default']
    QuoteServiceSelector: typeof import('./src/components/quotes/QuoteServiceSelector.vue')['default']
    QuoteStatusManager: typeof import('./src/components/quotes/QuoteStatusManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/ui/Select.vue')['default']
    ServiceForm: typeof import('./src/components/services/ServiceForm.vue')['default']
    ServiceList: typeof import('./src/components/services/ServiceList.vue')['default']
    ServiceSheetCard: typeof import('./src/components/services/ServiceSheetCard.vue')['default']
    ServiceSheetForm: typeof import('./src/components/services/ServiceSheetForm.vue')['default']
    SettlementForm: typeof import('./src/components/settlements/SettlementForm.vue')['default']
    Table: typeof import('./src/components/ui/Table.vue')['default']
  }
}
